In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(2)
b = tf.constant(3)
print(a)
sess = tf.Session()
l = tf.add(a, b)
print(l)
print(sess.run(l))
m = sess.run(a * b)
s = sess.run(a + b)
print(m, s)
sess.run([a * b, a + b])
a

Tensor("Const:0", shape=(), dtype=int32)
Tensor("Add:0", shape=(), dtype=int32)
5
6 5


<tf.Tensor 'Const:0' shape=() dtype=int32>

In [3]:
x = tf.placeholder(tf.int16)
y = tf.placeholder(tf.int16)
add = tf.add(x, y)
sess = tf.Session()
sess.run(add, feed_dict={x:10, y:20})

30

In [4]:
matrix1 = tf.constant([[3,3]])
matrix2 = tf.constant([[3],[3]])
product = tf.matmul(matrix1, matrix2)
with tf.Session() as sess:
    p = sess.run(product)
    print(p)
    

[[18]]


In [5]:
dummyinput = tf.constant([[1, 2], [3, 4]])
dummyweights = tf.constant([[4, 5, 6],[7, 8, 9]])
dummybiases = tf.constant([10,11,12])
product = tf.matmul(dummyinput, dummyweights)
sum1 = tf.add(product, dummybiases)
with tf.Session() as sess:
    p = sess.run(product)
    print(p)
    s = sess.run(sum1)
    print(s)

[[18 21 24]
 [40 47 54]]
[[28 32 36]
 [50 58 66]]


In [6]:
from tensorflow.examples.tutorials.mnist import input_data

Instructions for updating:
Use the retry module or similar alternatives.


In [7]:
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [8]:
mnist.train.images.shape
mnist.train.labels.shape

(55000, 10)

In [37]:
n_hidden_1 = 128
n_hidden_2 = 128
n_input = 784
n_classes = 10

weights = {
    'h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
    'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes]))#, trainable=False)
}

biases = {
    'h1': tf.Variable(tf.random_normal([n_hidden_1])),
    'h2': tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}


In [48]:
def mlp(x, weights, biases):
    layer1 = tf.add(tf.matmul(x, weights['h1']), biases['h1'])
    layer1 = tf.nn.relu(layer1)
    
    layer2 = tf.add(tf.matmul(layer1, weights['h2']), biases['h2'])
    layer2 = tf.nn.relu(layer2)
    
    out_layer = tf.add(tf.matmul(layer2, weights['out']), biases['out'])
    return out_layer

In [49]:
x = tf.placeholder("float", [None, n_input])
y = tf.placeholder("float", [None, n_classes])
pred = mlp(x, weights, biases)
pred

<tf.Tensor 'Add_14:0' shape=(?, 10) dtype=float32>

In [78]:
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred, labels=y))
optimize = tf.train.AdamOptimizer(learning_rate=0.0005).minimize(cost)

In [79]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
sess.run(weights["out"])

array([[-0.88882899, -0.62062103,  1.9597702 , ..., -0.47907096,
        -0.18715219,  0.11734305],
       [-0.95920587,  1.04994857,  0.9856981 , ..., -0.62334418,
         0.49605942, -0.56683391],
       [ 0.31885543, -0.29140234, -0.54044235, ...,  0.73404437,
         0.84131062, -0.97177237],
       ..., 
       [-0.97739971, -0.37203684,  0.56625396, ..., -1.38402927,
         0.17589708,  0.59731948],
       [ 0.11256911, -0.11093783,  1.90675151, ...,  0.59713697,
        -1.36790383,  1.58196557],
       [ 0.25863802, -0.91424716,  0.30136907, ..., -0.41897851,
         1.82033706, -0.29826993]], dtype=float32)

In [83]:
batch_size = 75
for i in range(100):
    num_batches = int(mnist.train.num_examples/batch_size)
    total_cost = 0
    for j in range(num_batches):
        batch_x, batch_y = mnist.train.next_batch(batch_size)
        _ , c = sess.run([optimize, cost], feed_dict={x:batch_x, y:batch_y})
        total_cost += c
    print(total_cost)

28.7539935206
16.1220293809
16.6842060398
16.0742947982
17.266328966
14.3271766202
13.4407080931
13.7146950467
8.14202992828
19.4308995205
15.0348581009
10.006085269
17.5501054169
14.8548780758
10.2015991972
8.10189961058
22.2845314653
8.00543376913
11.7763743898
14.2292372327
9.76787152481
15.6440665482
13.3621624132
8.97476283674
17.2984222395
13.125074738
18.0086327016
14.7709303908
9.05701617923
11.4808998691
11.9738165445
10.8672119147
7.9720613715
8.47896365957
13.0836212216
11.1905080164
11.2265685309
8.78414110236
14.5169094856
13.0609678361
12.0521865703
10.7158378906
8.54682686097
9.97141731998
11.0245602788
14.6660094677
5.2706101118
11.8782604096
12.5991388084
8.66771974107
12.0397098126
9.1611753716
5.26987991993
14.4016279111
14.900674938
15.1687378897
9.29018570389
12.8685225574
9.34349174933
9.06619663113
7.4317025411
6.5624330453
13.3940907333
6.80420147615
12.0436982923
12.6031495425
6.36769821527
10.343130448
9.27888457294
14.1461431378
4.78479745806
9.07412895005
12

In [84]:
predictions = tf.argmax(pred, 1)
correct_labels = tf.argmax(y, 1)
correct_predictions = tf.equal(predictions, correct_labels)
predictions,correct_predictions  = sess.run([predictions, correct_predictions], feed_dict={x:mnist.test.images,
                                              y:mnist.test.labels})


In [85]:
(correct_predictions == False).sum()

453

In [71]:
sess.run(weights["out"])

array([[-1.05943942, -1.41803384,  1.27320504, ..., -0.23477079,
        -0.17305094, -0.39230812],
       [-0.02654043, -0.98069835,  0.43334058, ...,  1.59795094,
        -0.53981543,  0.76896966],
       [-1.18972588, -0.64856166,  0.85743493, ..., -0.29921627,
         0.29331595,  0.38305911],
       ..., 
       [-0.00822695,  0.67737859, -1.20292521, ...,  0.55244541,
        -0.94044328,  0.68713552],
       [ 1.28683853, -0.46225548,  0.23407234, ..., -0.20331714,
         0.28431693, -0.26567221],
       [ 0.30216917,  0.61549771, -1.01469135, ..., -1.6571269 ,
         0.48466611,  0.44145507]], dtype=float32)