In [1]:
import numpy as np

In [2]:
def sig(z):
    return 1/(1-np.exp(-z))


In [16]:
def derivativeSig(sig_out):
    return sig_out*(1-sig_out)

In [8]:
x = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
y = np.array([[0,0,1,1]]).T

In [9]:
y

array([[0],
       [0],
       [1],
       [1]])

In [11]:
weights = 2*np.random.random((3,1)) - 1
weights

array([[ 0.59348401],
       [ 0.70203741],
       [-0.16038363]])

In [14]:
output0 = x
output1 = sig(output0.dot(weights))
output0.dot(weights)

array([[-0.16038363],
       [ 0.54165378],
       [ 0.43310038],
       [ 1.13513779]])

In [13]:
output1

array([[-5.74840989],
       [ 2.3911164 ],
       [ 2.84491292],
       [ 1.47357403]])

In [38]:
first_term = output1 - y
sec_term = derivativeSig(output1)
third_term = output0
first_two = first_term*sec_term
print(first_two.shape)
print(x)
net_change = output0.T.dot(first_two)


(4, 1)
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [39]:
net_change

array([[ -10.01372253],
       [  -8.28410325],
       [ 205.02857175]])

In [68]:
alpha = 0.001
weights = weights - alpha*net_change
weights

array([[  26.6391763 ,   26.29325245,  -16.36928255],
       [  22.59491381,   22.24898995,  -20.41354505],
       [-490.4312399 , -490.77716376, -533.43969875]])

In [69]:
w0 = 2*np.random.random((3,4)) - 1
w1 = 2*np.random.random((4,1)) - 1

In [70]:
layer0 = x
layer1 = sig(np.dot(layer0, w0))
layer2 = sig(np.dot(layer1, w1))

In [71]:
for i in range(0,10000):
    l2_error = layer2 - y
    l2_delta = l2_error * derivativeSig(layer2)
    net_change2 = np.dot(layer1.T, l2_delta)

    l1_error = l2_delta.dot(w1.T)
    l1_delta = l1_error *derivativeSig(layer1)
    net_change1 = np.dot(layer0.T, l1_delta)
    w0 = w0 - alpha*net_change1
    w1 = w1 - alpha*net_change2
layer2

array([[ 1.0049385 ],
       [ 1.69403646],
       [ 1.        ],
       [-4.01354325]])

In [3]:
import tensorflow

In [4]:
import keras

Using TensorFlow backend.
